added commandline args in projectCreate

diff --git a/.local/bin/scripts/projectCreate b/.local/bin/scripts/projectCreate
--- a/.local/bin/scripts/projectCreate
+++ b/.local/bin/scripts/projectCreate
@@ -1,100 +1,189 @@
 #!/bin/sh
 
-[[ -z $1 ]] && exit 0
+[[ -z $1 ]] && help
 
-if [[ "$1" == "gradle" ]]; then
-  printf "Project name: "
-  read -r project
-  mkdir -p $project || exit
-  cd $project
-  git init
-  printf "Main class: "
-  read -r project
-  mkdir -p src/main/java
-  mkdir -p src/main/resources
-  printf "bin/*\n.project\n.gradle/*\n.settings/*\n.classpath\nbuild/*\n" > .gitignore
-  printf "plugins{\n\tid 'java'\n}\njar {\n\tmanifest {\n\t\tattributes 'Main-Class': '$project'\n\t}\n}\n" > build.gradle
-  folder="$(echo $project | sed "s/\./\//g" | xargs dirname)"
-  class="$(echo $project | sed "s/\./\//g" | xargs basename)"
-  mkdir -p src/main/java/$folder
-  touch src/main/java/$folder/$class.java
-elif [ "$1" == "cpp" ] || [ "$1" = "c" ]; then
-  printf "Project name: "
-  read -r pname
-  mkdir $pname || exit
-  printf "Enter executable name: "
-  read -r exe_name
-  cd $pname
-  mkdir src
-  mkdir include
-  mkdir bin
-  mkdir debug
-  touch src/main.cc
-  git init
-  echo "cmake_minimum_required(VERSION 2.8.9)" >> CMakeLists.txt
-  echo "project($pname)" >> CMakeLists.txt
-  echo "include_directories(include)" >> CMakeLists.txt
-  echo 'file(GLOB_RECURSE SOURCES "src/*".cc)' >> CMakeLists.txt
-  echo "add_executable($exe_name \${SOURCES})" >> CMakeLists.txt
-  echo "install(TARGETS $exe_name DESTINATION /usr/bin)" >> CMakeLists.txt
-  echo "#!/bin/sh" >> build
-  echo 'if [[ -z $1 ]]; then' >> build
-    echo 'mkdir -p bin' >> build
-    echo 'cd bin' >> build
-    echo 'cmake ..' >> build
-    echo 'make' >> build
-  echo 'elif [[ "$1" == "install" ]]; then' >> build
-    echo 'mkdir -p bin' >> build
-    echo 'cd bin' >> build
-    echo 'cmake ..' >> build
-    echo 'sudo make install' >> build
-  echo 'elif [[ "$1" == "debug" ]]; then' >> build
-    echo 'mkdir -p debug' >> build
-    echo 'cd debug' >> build
-    echo 'cmake -DCMAKE_BUILD_TYPE=Debug ..' >> build
-    echo 'make' >> build
-  echo 'elif [[ "$1" == "project" ]]; then' >> build
-    echo 'mkdir -p bin' >> build
-    echo 'cd bin' >> build
-    echo 'cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..' >> build
-    echo 'cp compile_commands.json ..' >> build
-  echo 'fi' >> build
-  chmod u+x build
-  echo 'bin/*' >> .gitignore
-  echo 'debug/*' >> .gitignore
-  echo 'compile_commands.json' >> .gitignore
-  echo '.vimspector.json' >> .gitignore
-  echo '.clangd/*' >> .gitignore
-  echo '{' >> .vimspector.json
-  echo '"configurations": {' >> .vimspector.json
-  echo '"Launch": {' >> .vimspector.json
-  echo '"adapter": "vscode-cpptools",' >> .vimspector.json
-  echo '"configuration": {' >> .vimspector.json
-  echo '"request": "launch",' >> .vimspector.json
-  echo "\"program\": \"debug/$exe_name\"," >> .vimspector.json
-  echo "\"cwd\": \"`pwd`\"," >> .vimspector.json
-  echo '"externalConsole": true,' >> .vimspector.json
-  echo '"MIMode": "gdb"' >> .vimspector.json
-  echo '}' >> .vimspector.json
-  echo '}' >> .vimspector.json
-  echo '}' >> .vimspector.json
-  echo '}' >> .vimspector.json
-  ./build project
-elif [ "$1" == "py" ] || [ "$1" = "python" ]; then
-  printf "Project name: "
-  read -r pname
-  mkdir $pname || exit
-  _pname=$(echo $pname | sed -e 's/-/_/g')
-  mkdir -p $pname/docs
-  mkdir -p $pname/$_pname
-  mkdir -p $pname/tests
-  touch $pname/LICENSE
-  touch $pname/README.md
-  touch $pname/TODO.md
-  touch $pname/setup.py
-  touch $pname/.gitignore
-  touch $pname/install.sh
-  touch $pname/$_pname/__init__.py
-  touch $pname/$_pname/utils.py
-  touch $pname/$_pname/__main__.py
-fi
+git_init='false'
+
+while getopts "l:hgp:c:e:" flag; do
+    case "${flag}" in
+        g)
+            git_init='true'
+            ;;
+        l)
+            lang="${OPTARG}"
+            ;;
+        p)
+            project_name="${OPTARG}"
+            ;;
+        c)
+            class_name="${OPTARG}"
+            ;;
+        e)
+            exe_name="${OPTARG}"
+            ;;
+        h)
+            help
+            ;;
+    esac
+done
+
+echo $git_init
+echo $lang
+echo "$project_name"
+echo "$class_name"
+
+function gradle_init(){ # pass project name and class name
+
+    echo "$project_name"
+    echo "$class_name"
+
+  [[  -z $project_name || -z $class_name ]] && help && exit
+
+  mkdir -p $project_name || exit
+  mkdir -p $project_name/src/main/java
+  mkdir -p $project_name/src/main/resources
+
+  (
+    echo "bin/*"
+    echo ".project"
+    echo ".gradle/*"
+    echo ".settings/*"
+    echo ".classpath"
+    echo "build/*"
+  ) > $project_name/.gitignore
+
+  (
+    echo -e "plugins{"
+    echo -e "\tid 'java'"
+    echo -e "}"
+    echo -e "jar {"
+    echo -e "\tmanifest {"
+    echo -e "\t\tattributes 'Main-Class': '$class_name'"
+    echo -e "\t}\n}\n"
+  ) > $project_name/build.gradle
+
+  folder="$(echo $project_name | sed "s/\./\//g" | xargs dirname)"
+  class="$(echo $class_name | sed "s/\./\//g" | xargs basename)"
+  mkdir -p $project_name/src/main/java/$folder
+  touch $project_name/src/main/java/$folder/$class.java
+  [ "$git_init" == "true" ] && git init $project_name
+}
+
+function cpp_init(){ # pass pname and exe_name
+
+  [[  -z "$project_name" || -z "$exe_name" ]] && help && exit
+
+  mkdir $project_name || exit
+
+  mkdir $project_name/src
+  mkdir $project_name/include
+  mkdir $project_name/bin
+  mkdir $project_name/debug
+  touch $project_name/src/main.cc
+
+  (
+    echo "cmake_minimum_required(VERSION 2.8.9)"
+    echo "project($project_name)"
+    echo "include_directories(include)"
+    echo 'file(GLOB_RECURSE SOURCES "src/*".cc)'
+    echo "add_executable($exe_name \${SOURCES})"
+    echo "install(TARGETS $exe_name DESTINATION /usr/bin)"
+  ) > $project_name/CMakeLists.txt
+
+  (
+    echo "#!/bin/sh"
+    echo 'if [[ -z $1 ]]; then'
+    echo 'mkdir -p bin'
+    echo 'cd bin'
+    echo 'cmake ..'
+    echo 'make'
+    echo 'elif [[ "$1" == "install" ]]; then'
+    echo 'mkdir -p bin'
+    echo 'cd bin'
+    echo 'cmake ..'
+    echo 'sudo make install'
+    echo 'elif [[ "$1" == "debug" ]]; then'
+    echo 'mkdir -p debug'
+    echo 'cd debug'
+    echo 'cmake -DCMAKE_BUILD_TYPE=Debug ..'
+    echo 'make'
+    echo 'elif [[ "$1" == "project" ]]; then'
+    echo 'mkdir -p bin'
+    echo 'cd bin'
+    echo 'cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..'
+    echo 'cp compile_commands.json ..'
+    echo 'fi'
+    ) > $project_name/build
+
+  chmod u+x $project_name/build
+
+  (
+    echo 'bin/*'
+    echo 'debug/*'
+    echo 'compile_commands.json'
+    echo '.vimspector.json'
+    echo '.clangd/*'
+  ) > $project_name/.gitignore
+
+  (
+    echo '{'
+    echo '"configurations": {'
+    echo '"Launch": {'
+    echo '"adapter": "vscode-cpptools",'
+    echo '"configuration": {'
+    echo '"request": "launch",'
+    echo "\"program\": \"debug/$exe_name\","
+    echo "\"cwd\": \"`pwd`\"," >> .vimspector.json
+    echo '"externalConsole": true,'
+    echo '"MIMode": "gdb"'
+    echo '}'
+    echo '}'
+    echo '}'
+    echo '}'
+  ) > $project_name/.vimspector.json
+
+  [ "$git_init" == "true" ] && git init $project_name
+
+  cd $project_name && ./build project
+
+}
+
+function py_init(){
+
+  [[  -z "$project_name" ]] && help && exit
+  echo $project_name
+  mkdir $project_name || exit
+  _project_name=$(echo $project_name | sed -e 's/-/_/g')
+  mkdir -p $project_name/docs
+  mkdir -p $project_name/$_project_name
+  mkdir -p $project_name/tests
+  touch $project_name/LICENSE
+  touch $project_name/README.md
+  touch $project_name/TODO.md
+  touch $project_name/setup.py
+  touch $project_name/.gitignore
+  touch $project_name/install.sh
+  touch $project_name/$_project_name/__init__.py
+  touch $project_name/$_project_name/utils.py
+  touch $project_name/$_project_name/__main__.py
+  [ "$git_init" == "true" ] && git init $project_name
+
+}
+
+function help(){
+  echo "usage: projectCreate -l lang -p projectName -c className"
+  echo "optional : -g intialise a git repo inside project folder"
+  echo "         : -h show this help message"
+}
+
+case $lang in
+  py )
+    py_init
+    ;;
+  c|cpp )
+    cpp_init
+    ;;
+  gradle )
+    gradle_init
+    ;;
+esac
